INFO :: 2025-01-12 21:17:57,044 :: uvicorn.error :: __init__ :: Will watch for changes in these directories: ['/home/uti/Documents/FastAPI/api/src']
INFO :: 2025-01-12 21:17:57,045 :: uvicorn.error :: bind_socket :: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO :: 2025-01-12 21:17:57,045 :: uvicorn.error :: startup :: Started reloader process [63020] using WatchFiles
INFO :: 2025-01-12 21:17:57,604 :: uvicorn.error :: _serve :: Started server process [63023]
INFO :: 2025-01-12 21:17:57,605 :: uvicorn.error :: startup :: Waiting for application startup.
ERROR :: 2025-01-12 21:17:57,688 :: uvicorn.error :: send :: Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2423, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1368, in _join_condition
    cls._joincond_trim_constraints(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1513, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'Join object on audit(138127850211136) and user(138127836424064)' and 'Join object on audit(138127850211136) and otp(138127834665600)'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 33, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 22, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 74, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 127, in get_user_by_username
    users = await self.async_session.execute(stmt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1632, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 703, in _compile_w_cache
    compiled_sql = self._compiler(
                   ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 316, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1429, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 870, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4679, in visit_select
    compile_state = select_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 683, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 1110, in create_for_statement
    _QueryEntity.to_compile_state(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2565, in to_compile_state
    _MapperEntity(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2645, in __init__
    entity._post_inspect
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4256, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2416, in _post_configure_properties
    prop.init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
    self.do_init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1644, in do_init
    self._setup_join_conditions()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1884, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2310, in __init__
    self._determine_joins()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2467, in _determine_joins
    raise sa_exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship User.otp - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

ERROR :: 2025-01-12 21:17:57,695 :: uvicorn.error :: startup :: Application startup failed. Exiting.
INFO :: 2025-01-12 21:18:28,227 :: uvicorn.error :: shutdown :: Stopping reloader process [63020]
INFO :: 2025-01-12 21:21:57,147 :: uvicorn.error :: __init__ :: Will watch for changes in these directories: ['/home/uti/Documents/FastAPI/api/src']
INFO :: 2025-01-12 21:21:57,147 :: uvicorn.error :: bind_socket :: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO :: 2025-01-12 21:21:57,148 :: uvicorn.error :: startup :: Started reloader process [64314] using WatchFiles
INFO :: 2025-01-12 21:21:57,694 :: uvicorn.error :: _serve :: Started server process [64329]
INFO :: 2025-01-12 21:21:57,695 :: uvicorn.error :: startup :: Waiting for application startup.
ERROR :: 2025-01-12 21:21:57,753 :: uvicorn.error :: send :: Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 534, in _prepare_and_execute
    self._rows = deque(await prepared_stmt.fetch(*parameters))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/asyncpg/prepared_stmt.py", line 267, in __bind_execute
    data, status, _ = await self.__do_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/asyncpg/prepared_stmt.py", line 256, in __do_execute
    return await executor(protocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 206, in bind_execute
asyncpg.exceptions.DependentObjectsStillExistError: cannot drop table audit because other objects depend on it
DETAIL:  constraint otps_id_fkey on table otps depends on table audit
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 568, in execute
    self._adapt_connection.await_(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 546, in _prepare_and_execute
    self._handle_exception(error)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 497, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 780, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.Error: <class 'asyncpg.exceptions.DependentObjectsStillExistError'>: cannot drop table audit because other objects depend on it
DETAIL:  constraint otps_id_fkey on table otps depends on table audit
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 33, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 22, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 72, in create_tables
    await conn.run_sync(Base.metadata.drop_all)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 886, in run_sync
    return await greenlet_spawn(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/schema.py", line 5896, in drop_all
    bind._run_ddl_visitor(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2459, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 664, in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py", line 1076, in visit_metadata
    self.traverse_single(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 664, in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py", line 1143, in visit_table
    DropTable(table)._invoke_with(self.connection)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py", line 314, in _invoke_with
    return bind.execute(self)
           ^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py", line 180, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1529, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 568, in execute
    self._adapt_connection.await_(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 546, in _prepare_and_execute
    self._handle_exception(error)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 497, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 780, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DependentObjectsStillExistError'>: cannot drop table audit because other objects depend on it
DETAIL:  constraint otps_id_fkey on table otps depends on table audit
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
[SQL: 
DROP TABLE audit]
(Background on this error at: https://sqlalche.me/e/20/dbapi)

ERROR :: 2025-01-12 21:21:57,760 :: uvicorn.error :: startup :: Application startup failed. Exiting.
INFO :: 2025-01-12 21:22:25,991 :: uvicorn.error :: shutdown :: Stopping reloader process [64314]
INFO :: 2025-01-12 21:37:19,882 :: uvicorn.error :: __init__ :: Will watch for changes in these directories: ['/home/uti/Documents/FastAPI/api/src']
INFO :: 2025-01-12 21:37:19,883 :: uvicorn.error :: bind_socket :: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO :: 2025-01-12 21:37:19,883 :: uvicorn.error :: startup :: Started reloader process [69370] using WatchFiles
INFO :: 2025-01-12 21:37:20,432 :: uvicorn.error :: _serve :: Started server process [69379]
INFO :: 2025-01-12 21:37:20,434 :: uvicorn.error :: startup :: Waiting for application startup.
ERROR :: 2025-01-12 21:37:20,554 :: uvicorn.error :: send :: Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2423, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1368, in _join_condition
    cls._joincond_trim_constraints(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1513, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'Join object on audit(129066471447088) and user(129066471450304)' and 'Join object on audit(129066471447088) and otp(129066469691744)'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 33, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 22, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 74, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 127, in get_user_by_username
    users = await self.async_session.execute(stmt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1632, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 703, in _compile_w_cache
    compiled_sql = self._compiler(
                   ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 316, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1429, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 870, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4679, in visit_select
    compile_state = select_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 683, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 1110, in create_for_statement
    _QueryEntity.to_compile_state(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2565, in to_compile_state
    _MapperEntity(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2645, in __init__
    entity._post_inspect
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4256, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2416, in _post_configure_properties
    prop.init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
    self.do_init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1644, in do_init
    self._setup_join_conditions()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1884, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2310, in __init__
    self._determine_joins()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2467, in _determine_joins
    raise sa_exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship User.otp - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

ERROR :: 2025-01-12 21:37:20,561 :: uvicorn.error :: startup :: Application startup failed. Exiting.
INFO :: 2025-01-12 21:37:27,656 :: uvicorn.error :: shutdown :: Stopping reloader process [69370]
INFO :: 2025-01-12 21:38:58,216 :: uvicorn.error :: __init__ :: Will watch for changes in these directories: ['/home/uti/Documents/FastAPI/api/src']
INFO :: 2025-01-12 21:38:58,217 :: uvicorn.error :: bind_socket :: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO :: 2025-01-12 21:38:58,217 :: uvicorn.error :: startup :: Started reloader process [69920] using WatchFiles
INFO :: 2025-01-12 21:38:58,774 :: uvicorn.error :: _serve :: Started server process [69928]
INFO :: 2025-01-12 21:38:58,775 :: uvicorn.error :: startup :: Waiting for application startup.
ERROR :: 2025-01-12 21:38:58,918 :: uvicorn.error :: send :: Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2423, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1368, in _join_condition
    cls._joincond_trim_constraints(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1513, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'Join object on audit(132745159268336) and user(132745159271696)' and 'Join object on audit(132745159268336) and otp(132745157496848)'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 33, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 22, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 74, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 127, in get_user_by_username
    users = await self.async_session.execute(stmt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1632, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 703, in _compile_w_cache
    compiled_sql = self._compiler(
                   ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 316, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1429, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 870, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4679, in visit_select
    compile_state = select_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 683, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 1110, in create_for_statement
    _QueryEntity.to_compile_state(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2565, in to_compile_state
    _MapperEntity(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2645, in __init__
    entity._post_inspect
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4256, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2416, in _post_configure_properties
    prop.init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
    self.do_init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1644, in do_init
    self._setup_join_conditions()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1884, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2310, in __init__
    self._determine_joins()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2467, in _determine_joins
    raise sa_exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship User.otp - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

ERROR :: 2025-01-12 21:38:58,925 :: uvicorn.error :: startup :: Application startup failed. Exiting.
DEBUG :: 2025-01-12 21:39:48,509 :: watchfiles.main :: _log_changes :: 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/users.py')}
WARNING :: 2025-01-12 21:39:48,510 :: uvicorn.error :: run :: WatchFiles detected changes in 'modules/repository/schema/users.py'. Reloading...
DEBUG :: 2025-01-12 21:39:48,961 :: watchfiles.main :: _log_changes :: 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.135023233079680'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.135023233079680')}
INFO :: 2025-01-12 21:39:49,061 :: uvicorn.error :: _serve :: Started server process [70192]
INFO :: 2025-01-12 21:39:49,062 :: uvicorn.error :: startup :: Waiting for application startup.
ERROR :: 2025-01-12 21:39:49,217 :: uvicorn.error :: send :: Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2423, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1368, in _join_condition
    cls._joincond_trim_constraints(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1513, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'Join object on audit(135023205260688) and user(135023205263472)' and 'Join object on audit(135023205260688) and otp(135023203487520)'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 33, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 22, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 74, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 127, in get_user_by_username
    users = await self.async_session.execute(stmt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1632, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 703, in _compile_w_cache
    compiled_sql = self._compiler(
                   ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 316, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1429, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 870, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4679, in visit_select
    compile_state = select_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 683, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 1110, in create_for_statement
    _QueryEntity.to_compile_state(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2565, in to_compile_state
    _MapperEntity(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2645, in __init__
    entity._post_inspect
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4256, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2416, in _post_configure_properties
    prop.init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
    self.do_init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1644, in do_init
    self._setup_join_conditions()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1884, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2310, in __init__
    self._determine_joins()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2467, in _determine_joins
    raise sa_exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship User.otp - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

ERROR :: 2025-01-12 21:39:49,224 :: uvicorn.error :: startup :: Application startup failed. Exiting.
DEBUG :: 2025-01-12 21:39:54,923 :: watchfiles.main :: _log_changes :: 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/users.py')}
WARNING :: 2025-01-12 21:39:54,923 :: uvicorn.error :: run :: WatchFiles detected changes in 'modules/repository/schema/users.py'. Reloading...
DEBUG :: 2025-01-12 21:39:55,374 :: watchfiles.main :: _log_changes :: 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.127426261997952'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.127426261997952'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc')}
DEBUG :: 2025-01-12 21:40:07,903 :: watchfiles.main :: _log_changes :: 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/users.py')}
WARNING :: 2025-01-12 21:40:07,903 :: uvicorn.error :: run :: WatchFiles detected changes in 'modules/repository/schema/users.py'. Reloading...
DEBUG :: 2025-01-12 21:40:08,355 :: watchfiles.main :: _log_changes :: 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.130608312834432'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.130608312834432')}
DEBUG :: 2025-01-12 21:40:10,761 :: watchfiles.main :: _log_changes :: 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/users.py')}
WARNING :: 2025-01-12 21:40:10,761 :: uvicorn.error :: run :: WatchFiles detected changes in 'modules/repository/schema/users.py'. Reloading...
DEBUG :: 2025-01-12 21:40:11,212 :: watchfiles.main :: _log_changes :: 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.124564598905216'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.124564598905216')}
INFO :: 2025-01-12 21:40:11,313 :: uvicorn.error :: _serve :: Started server process [70439]
INFO :: 2025-01-12 21:40:11,314 :: uvicorn.error :: startup :: Waiting for application startup.
ERROR :: 2025-01-12 21:40:11,466 :: uvicorn.error :: send :: Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2423, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1368, in _join_condition
    cls._joincond_trim_constraints(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1513, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'Join object on audit(124564570872416) and user(124564571230656)' and 'Join object on audit(124564570872416) and otp(124564569116880)'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 33, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 22, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 74, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 127, in get_user_by_username
    users = await self.async_session.execute(stmt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1632, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 703, in _compile_w_cache
    compiled_sql = self._compiler(
                   ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 316, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1429, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 870, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4679, in visit_select
    compile_state = select_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 683, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 1110, in create_for_statement
    _QueryEntity.to_compile_state(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2565, in to_compile_state
    _MapperEntity(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2645, in __init__
    entity._post_inspect
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4256, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2416, in _post_configure_properties
    prop.init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
    self.do_init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1644, in do_init
    self._setup_join_conditions()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1884, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2310, in __init__
    self._determine_joins()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2467, in _determine_joins
    raise sa_exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship User.otp - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

ERROR :: 2025-01-12 21:40:11,473 :: uvicorn.error :: startup :: Application startup failed. Exiting.
INFO :: 2025-01-12 21:40:15,475 :: uvicorn.error :: shutdown :: Stopping reloader process [69920]
INFO :: 2025-01-12 21:40:17,660 :: uvicorn.error :: __init__ :: Will watch for changes in these directories: ['/home/uti/Documents/FastAPI/api/src']
INFO :: 2025-01-12 21:40:17,661 :: uvicorn.error :: bind_socket :: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO :: 2025-01-12 21:40:17,661 :: uvicorn.error :: startup :: Started reloader process [70525] using WatchFiles
INFO :: 2025-01-12 21:40:18,202 :: uvicorn.error :: _serve :: Started server process [70527]
INFO :: 2025-01-12 21:40:18,203 :: uvicorn.error :: startup :: Waiting for application startup.
ERROR :: 2025-01-12 21:40:18,352 :: uvicorn.error :: send :: Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2423, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1368, in _join_condition
    cls._joincond_trim_constraints(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1513, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'Join object on audit(137136552499424) and user(137136552502832)' and 'Join object on audit(137136552499424) and otp(137136550728224)'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 33, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 22, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 74, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 127, in get_user_by_username
    users = await self.async_session.execute(stmt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1632, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 703, in _compile_w_cache
    compiled_sql = self._compiler(
                   ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 316, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1429, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 870, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4679, in visit_select
    compile_state = select_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 683, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 1110, in create_for_statement
    _QueryEntity.to_compile_state(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2565, in to_compile_state
    _MapperEntity(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2645, in __init__
    entity._post_inspect
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4256, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2416, in _post_configure_properties
    prop.init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
    self.do_init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1644, in do_init
    self._setup_join_conditions()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1884, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2310, in __init__
    self._determine_joins()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2467, in _determine_joins
    raise sa_exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship User.otp - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

ERROR :: 2025-01-12 21:40:18,360 :: uvicorn.error :: startup :: Application startup failed. Exiting.
DEBUG :: 2025-01-12 21:40:57,803 :: watchfiles.main :: _log_changes :: 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/users.py')}
WARNING :: 2025-01-12 21:40:57,804 :: uvicorn.error :: run :: WatchFiles detected changes in 'modules/repository/schema/users.py'. Reloading...
DEBUG :: 2025-01-12 21:40:58,255 :: watchfiles.main :: _log_changes :: 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.135282818570624'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.135282818570624')}
INFO :: 2025-01-12 21:40:58,375 :: uvicorn.error :: _serve :: Started server process [70779]
INFO :: 2025-01-12 21:40:58,376 :: uvicorn.error :: startup :: Waiting for application startup.
ERROR :: 2025-01-12 21:40:58,527 :: uvicorn.error :: send :: Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2423, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1368, in _join_condition
    cls._joincond_trim_constraints(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1513, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'Join object on audit(135282790767056) and user(135282790770272)' and 'Join object on audit(135282790767056) and otp(135282788995520)'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 33, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 22, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 74, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 127, in get_user_by_username
    users = await self.async_session.execute(stmt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1632, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 703, in _compile_w_cache
    compiled_sql = self._compiler(
                   ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 316, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1429, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 870, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4679, in visit_select
    compile_state = select_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 683, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 1110, in create_for_statement
    _QueryEntity.to_compile_state(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2565, in to_compile_state
    _MapperEntity(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2645, in __init__
    entity._post_inspect
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4256, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2416, in _post_configure_properties
    prop.init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
    self.do_init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1644, in do_init
    self._setup_join_conditions()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1884, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2310, in __init__
    self._determine_joins()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2467, in _determine_joins
    raise sa_exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship User.otp - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

ERROR :: 2025-01-12 21:40:58,535 :: uvicorn.error :: startup :: Application startup failed. Exiting.
DEBUG :: 2025-01-12 21:41:00,761 :: watchfiles.main :: _log_changes :: 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/users.py')}
WARNING :: 2025-01-12 21:41:00,761 :: uvicorn.error :: run :: WatchFiles detected changes in 'modules/repository/schema/users.py'. Reloading...
DEBUG :: 2025-01-12 21:41:01,262 :: watchfiles.main :: _log_changes :: 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.140166426139008'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.140166426139008')}
INFO :: 2025-01-12 21:41:01,340 :: uvicorn.error :: _serve :: Started server process [70832]
INFO :: 2025-01-12 21:41:01,342 :: uvicorn.error :: startup :: Waiting for application startup.
ERROR :: 2025-01-12 21:41:01,493 :: uvicorn.error :: send :: Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2423, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1368, in _join_condition
    cls._joincond_trim_constraints(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1513, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'Join object on audit(140166398123168) and user(140166398125664)' and 'Join object on audit(140166398123168) and otp(140166396350720)'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 33, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 22, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 74, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 127, in get_user_by_username
    users = await self.async_session.execute(stmt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1632, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 703, in _compile_w_cache
    compiled_sql = self._compiler(
                   ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 316, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1429, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 870, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4679, in visit_select
    compile_state = select_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 683, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 1110, in create_for_statement
    _QueryEntity.to_compile_state(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2565, in to_compile_state
    _MapperEntity(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2645, in __init__
    entity._post_inspect
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4256, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2416, in _post_configure_properties
    prop.init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
    self.do_init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1644, in do_init
    self._setup_join_conditions()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1884, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2310, in __init__
    self._determine_joins()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2467, in _determine_joins
    raise sa_exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship User.otp - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

ERROR :: 2025-01-12 21:41:01,500 :: uvicorn.error :: startup :: Application startup failed. Exiting.
DEBUG :: 2025-01-12 21:41:01,813 :: watchfiles.main :: _log_changes :: 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/users.py')}
WARNING :: 2025-01-12 21:41:01,814 :: uvicorn.error :: run :: WatchFiles detected changes in 'modules/repository/schema/users.py'. Reloading...
DEBUG :: 2025-01-12 21:41:02,265 :: watchfiles.main :: _log_changes :: 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.131089810561408'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.131089810561408'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc')}
INFO :: 2025-01-12 21:41:02,381 :: uvicorn.error :: _serve :: Started server process [70842]
INFO :: 2025-01-12 21:41:02,382 :: uvicorn.error :: startup :: Waiting for application startup.
ERROR :: 2025-01-12 21:41:02,531 :: uvicorn.error :: send :: Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2423, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1368, in _join_condition
    cls._joincond_trim_constraints(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1513, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'Join object on audit(131089782758512) and user(131089782761728)' and 'Join object on audit(131089782758512) and otp(131089781002976)'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 33, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 22, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 74, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 127, in get_user_by_username
    users = await self.async_session.execute(stmt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1632, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 703, in _compile_w_cache
    compiled_sql = self._compiler(
                   ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 316, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1429, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 870, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4679, in visit_select
    compile_state = select_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 683, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 1110, in create_for_statement
    _QueryEntity.to_compile_state(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2565, in to_compile_state
    _MapperEntity(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2645, in __init__
    entity._post_inspect
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4256, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2416, in _post_configure_properties
    prop.init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
    self.do_init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1644, in do_init
    self._setup_join_conditions()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1884, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2310, in __init__
    self._determine_joins()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2467, in _determine_joins
    raise sa_exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship User.otp - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

ERROR :: 2025-01-12 21:41:02,538 :: uvicorn.error :: startup :: Application startup failed. Exiting.
DEBUG :: 2025-01-12 21:44:23,868 :: watchfiles.main :: _log_changes :: 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/users.py')}
WARNING :: 2025-01-12 21:44:23,868 :: uvicorn.error :: run :: WatchFiles detected changes in 'modules/repository/schema/users.py'. Reloading...
DEBUG :: 2025-01-12 21:44:24,320 :: watchfiles.main :: _log_changes :: 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.135534285953408'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.135534285953408'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc')}
INFO :: 2025-01-12 21:44:24,423 :: uvicorn.error :: _serve :: Started server process [71736]
INFO :: 2025-01-12 21:44:24,424 :: uvicorn.error :: startup :: Waiting for application startup.
ERROR :: 2025-01-12 21:44:24,564 :: uvicorn.error :: send :: Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2423, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1368, in _join_condition
    cls._joincond_trim_constraints(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1513, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'Join object on audit(135534258132736) and user(135534258136000)' and 'Join object on audit(135534258132736) and otp(135534256377680)'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 33, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 22, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 74, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 127, in get_user_by_username
    users = await self.async_session.execute(stmt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1632, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 703, in _compile_w_cache
    compiled_sql = self._compiler(
                   ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 316, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1429, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 870, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4679, in visit_select
    compile_state = select_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 683, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 1110, in create_for_statement
    _QueryEntity.to_compile_state(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2565, in to_compile_state
    _MapperEntity(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2645, in __init__
    entity._post_inspect
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4256, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2416, in _post_configure_properties
    prop.init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
    self.do_init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1644, in do_init
    self._setup_join_conditions()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1884, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2310, in __init__
    self._determine_joins()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2467, in _determine_joins
    raise sa_exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship User.otp - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

ERROR :: 2025-01-12 21:44:24,571 :: uvicorn.error :: startup :: Application startup failed. Exiting.
DEBUG :: 2025-01-12 21:44:32,790 :: watchfiles.main :: _log_changes :: 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/users.py')}
WARNING :: 2025-01-12 21:44:32,790 :: uvicorn.error :: run :: WatchFiles detected changes in 'modules/repository/schema/users.py'. Reloading...
DEBUG :: 2025-01-12 21:44:34,243 :: watchfiles.main :: _log_changes :: 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/users.py')}
WARNING :: 2025-01-12 21:44:34,244 :: uvicorn.error :: run :: WatchFiles detected changes in 'modules/repository/schema/users.py'. Reloading...
DEBUG :: 2025-01-12 21:44:34,696 :: watchfiles.main :: _log_changes :: 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.128211850107264'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.128211850107264'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc')}
INFO :: 2025-01-12 21:44:34,820 :: uvicorn.error :: _serve :: Started server process [71859]
INFO :: 2025-01-12 21:44:34,822 :: uvicorn.error :: startup :: Waiting for application startup.
ERROR :: 2025-01-12 21:44:34,990 :: uvicorn.error :: send :: Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2423, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1368, in _join_condition
    cls._joincond_trim_constraints(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1513, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'Join object on audit(128211822286976) and user(128211822290432)' and 'Join object on audit(128211822286976) and otp(128211820515632)'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 33, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 22, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 74, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 127, in get_user_by_username
    users = await self.async_session.execute(stmt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1632, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 703, in _compile_w_cache
    compiled_sql = self._compiler(
                   ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 316, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1429, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 870, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4679, in visit_select
    compile_state = select_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 683, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 1110, in create_for_statement
    _QueryEntity.to_compile_state(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2565, in to_compile_state
    _MapperEntity(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2645, in __init__
    entity._post_inspect
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4256, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2416, in _post_configure_properties
    prop.init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
    self.do_init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1644, in do_init
    self._setup_join_conditions()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1884, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2310, in __init__
    self._determine_joins()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2467, in _determine_joins
    raise sa_exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship User.otp - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

ERROR :: 2025-01-12 21:44:34,997 :: uvicorn.error :: startup :: Application startup failed. Exiting.
DEBUG :: 2025-01-12 21:44:43,515 :: watchfiles.main :: _log_changes :: 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/users.py')}
WARNING :: 2025-01-12 21:44:43,516 :: uvicorn.error :: run :: WatchFiles detected changes in 'modules/repository/schema/users.py'. Reloading...
DEBUG :: 2025-01-12 21:44:43,967 :: watchfiles.main :: _log_changes :: 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.128947469179264'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.128947469179264'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc')}
INFO :: 2025-01-12 21:44:44,087 :: uvicorn.error :: _serve :: Started server process [71972]
INFO :: 2025-01-12 21:44:44,088 :: uvicorn.error :: startup :: Waiting for application startup.
ERROR :: 2025-01-12 21:44:44,228 :: uvicorn.error :: send :: Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2423, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1368, in _join_condition
    cls._joincond_trim_constraints(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1513, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'otp' and 'Join object on audit(128947446903776) and user(128947441379200)'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 33, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 22, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 74, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 127, in get_user_by_username
    users = await self.async_session.execute(stmt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1632, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 703, in _compile_w_cache
    compiled_sql = self._compiler(
                   ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 316, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1429, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 870, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4679, in visit_select
    compile_state = select_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 683, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 1110, in create_for_statement
    _QueryEntity.to_compile_state(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2565, in to_compile_state
    _MapperEntity(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2645, in __init__
    entity._post_inspect
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4256, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2416, in _post_configure_properties
    prop.init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
    self.do_init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1644, in do_init
    self._setup_join_conditions()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1884, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2310, in __init__
    self._determine_joins()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2467, in _determine_joins
    raise sa_exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship Otp.owner - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

ERROR :: 2025-01-12 21:44:44,235 :: uvicorn.error :: startup :: Application startup failed. Exiting.
DEBUG :: 2025-01-12 21:44:46,524 :: watchfiles.main :: _log_changes :: 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/users.py')}
WARNING :: 2025-01-12 21:44:46,524 :: uvicorn.error :: run :: WatchFiles detected changes in 'modules/repository/schema/users.py'. Reloading...
DEBUG :: 2025-01-12 21:44:47,026 :: watchfiles.main :: _log_changes :: 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.129307352504704'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.129307352504704'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc')}
INFO :: 2025-01-12 21:44:47,103 :: uvicorn.error :: _serve :: Started server process [72059]
INFO :: 2025-01-12 21:44:47,105 :: uvicorn.error :: startup :: Waiting for application startup.
ERROR :: 2025-01-12 21:44:47,248 :: uvicorn.error :: send :: Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2423, in _determine_joins
    self.primaryjoin = join_condition(
                       ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/util.py", line 123, in join_condition
    return Join._join_condition(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1368, in _join_condition
    cls._joincond_trim_constraints(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/selectable.py", line 1513, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'otp' and 'Join object on audit(129307324243248) and user(129307324245936)'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 33, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 22, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 74, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 127, in get_user_by_username
    users = await self.async_session.execute(stmt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1632, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 703, in _compile_w_cache
    compiled_sql = self._compiler(
                   ^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 316, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 1429, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 870, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 915, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 141, in _compiler_dispatch
    return meth(self, **kw)  # type: ignore  # noqa: E501
           ^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 4679, in visit_select
    compile_state = select_stmt._compile_state_factory(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 683, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 1110, in create_for_statement
    _QueryEntity.to_compile_state(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2565, in to_compile_state
    _MapperEntity(
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 2645, in __init__
    entity._post_inspect
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2722, in _post_inspect
    self._check_configure()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2399, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4215, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 4256, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/mapper.py", line 2416, in _post_configure_properties
    prop.init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/interfaces.py", line 589, in init
    self.do_init()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1644, in do_init
    self._setup_join_conditions()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 1884, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
                                ^^^^^^^^^^^^^^
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2310, in __init__
    self._determine_joins()
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/relationships.py", line 2467, in _determine_joins
    raise sa_exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship Otp.owner - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

ERROR :: 2025-01-12 21:44:47,255 :: uvicorn.error :: startup :: Application startup failed. Exiting.
DEBUG :: 2025-01-12 21:45:01,718 :: watchfiles.main :: _log_changes :: 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/users.py')}
WARNING :: 2025-01-12 21:45:01,719 :: uvicorn.error :: run :: WatchFiles detected changes in 'modules/repository/schema/users.py'. Reloading...
DEBUG :: 2025-01-12 21:45:02,170 :: watchfiles.main :: _log_changes :: 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.124541967063424'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc.124541967063424'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/repository/schema/__pycache__/users.cpython-312.pyc')}
INFO :: 2025-01-12 21:45:02,282 :: uvicorn.error :: _serve :: Started server process [72145]
INFO :: 2025-01-12 21:45:02,284 :: uvicorn.error :: startup :: Waiting for application startup.
INFO :: 2025-01-12 21:45:02,427 :: fastapi :: create_admin_account :: account with id 51d2349d-23dd-4e35-bcb3-ea1d6b0ccf99 created
INFO :: 2025-01-12 21:45:02,427 :: fastapi :: on_api_start :: FastAPI Application: v1.0 is starting.
INFO :: 2025-01-12 21:45:02,427 :: uvicorn.error :: startup :: Application startup complete.
DEBUG :: 2025-01-12 21:45:35,255 :: watchfiles.main :: _log_changes :: 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/service/otp.py')}
WARNING :: 2025-01-12 21:45:35,256 :: uvicorn.error :: run :: WatchFiles detected changes in 'modules/service/otp.py'. Reloading...
INFO :: 2025-01-12 21:45:35,323 :: uvicorn.error :: shutdown :: Shutting down
INFO :: 2025-01-12 21:45:35,424 :: uvicorn.error :: shutdown :: Waiting for application shutdown.
INFO :: 2025-01-12 21:45:35,427 :: fastapi :: on_api_shuttdown :: FastAPI Application: v1.0 is shutting down.
INFO :: 2025-01-12 21:45:35,427 :: uvicorn.error :: shutdown :: Application shutdown complete.
INFO :: 2025-01-12 21:45:35,427 :: uvicorn.error :: _serve :: Finished server process [72145]
INFO :: 2025-01-12 21:45:35,988 :: uvicorn.error :: _serve :: Started server process [72343]
INFO :: 2025-01-12 21:45:35,990 :: uvicorn.error :: startup :: Waiting for application startup.
INFO :: 2025-01-12 21:45:36,151 :: fastapi :: create_admin_account :: account with id 299246e7-e1c3-4d32-a227-c948a599c945 created
INFO :: 2025-01-12 21:45:36,151 :: fastapi :: on_api_start :: FastAPI Application: v1.0 is starting.
INFO :: 2025-01-12 21:45:36,151 :: uvicorn.error :: startup :: Application startup complete.
INFO :: 2025-01-12 21:48:33,380 :: uvicorn.error :: shutdown :: Shutting down
INFO :: 2025-01-12 21:48:33,481 :: uvicorn.error :: shutdown :: Waiting for application shutdown.
INFO :: 2025-01-12 21:48:33,484 :: fastapi :: on_api_shuttdown :: FastAPI Application: v1.0 is shutting down.
INFO :: 2025-01-12 21:48:33,484 :: uvicorn.error :: shutdown :: Application shutdown complete.
INFO :: 2025-01-12 21:48:33,485 :: uvicorn.error :: _serve :: Finished server process [72343]
INFO :: 2025-01-12 21:48:33,489 :: uvicorn.error :: shutdown :: Stopping reloader process [70525]
